name: E2E (Cypress)

on:
  workflow_dispatch:          # manual “Run workflow” button
  pull_request:
    branches: [ "**" ]
    paths:
      - ".github/**"
      - "cypress/**"
      - "package.json"
      - "package-lock.json"
      - "cypress.config.*"
      - "**/*.ts"
      - "**/*.js"
      - "README.md"
  push:
    branches: [ "**" ]
    paths:
      - ".github/**"
      - "cypress/**"
      - "package.json"
      - "package-lock.json"
      - "cypress.config.*"
      - "**/*.ts"
      - "**/*.js"
      - "README.md"

concurrency:
  group: cypress-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Run Cypress (headless, Chrome) + build report
        run: npm run test:ci
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          if-no-files-found: ignore
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos
